title: Cyber Security Pilot
description: From Chaos to Cadence - A modern approach to cyber security.
url: "https://techmore.github.io"
baseurl: "/CyberSecurityPilot.github.io"
github_username: techmore

plugins:
  - jekyll-seo-tag

show_excerpts: false

theme: null
